# Generated by Django 5.1 on 2024-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(default='Jane', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='lastname',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
