# Generated by Django 5.1 on 2024-08-27 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_healthinfo_user_healthworkerinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworkerinfo',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('uid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_consultations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
