# Generated by Django 5.1 on 2024-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_healthworkerinfo_is_available_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
