# Generated by Django 5.1 on 2024-08-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consultation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='user',
            new_name='patient',
        ),
    ]
