# Generated by Django 5.1 on 2024-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_consultation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='app_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
